# ===== App =====
spring.application.name=simon
server.port=8081

# ===== DB (usuarios) =====
spring.datasource.url=jdbc:mysql://localhost:3306/baseropa?useSSL=false&serverTimezone=America/Santiago
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

# ===== JWT (clave de al menos 256 bits para HS256) =====
app.jwt.secret=esta_es_una_clave_ultra_secreta_de_mas_de_32_caracteres_123456   # cámbiala en producción
app.jwt.expiration-ms=3600000     # 1 hora
app.jwt.issuer=simon-api

# ===== CORS (origins del front) =====
app.cors.allowed-origins=http://localhost:5173,http://127.0.0.1:5173

